### ISSUE TITLE
algo.py的ElectronicEyeAlgo.send_short()方法下有多余类属性self.order_ask_price, self.order_ask_volume

### ISSUE THREAD

**Issue by ZackChang007** [vnpy/vnpy_optionmaster#18]
1. 蓝框圈出的两个类属性并未在类中定义，而且全局搜索整个repo也发现这两个类变量只在这里出现了一次（参见附图1、附图2）；
2. 在send_long(), send_short()这两个功能类似的类方法中，只有send_short()中出现了这两个类属性。
3. 因此，不确定这两个类属性有什么用，目前看起来是多余的，也可能有什么基于这两个类属性的功能暂未实现。
<img width="1099" alt="微信图片_20241106154057" src="https://github.com/user-attachments/assets/98e4ec25-99cb-4cbd-b567-4882363c5a41">
<img width="815" alt="微信图片_20241106154042" src="https://github.com/user-attachments/assets/9e3b13ce-22b9-4b1d-85dd-f3d7bb4596cd">

**Comment by vnpy** [comment]
感谢反馈，我们会在下个版本中处理修复
