### ISSUE TITLE
希腊值风险不能正确显示

### ISSUE THREAD

**Issue by JudgeAllen** [vnpy/vnpy_optionmaster#8]
利用Paper测试时，希腊值风险不显示任何持仓相关数据
未测试实盘

**Comment by vnpy** [comment]
请提供下相关截图？

**Comment by JudgeAllen** [comment]
![微信图片_20220309081950](https://user-images.githubusercontent.com/4287323/157348350-55bd0ac7-5955-44cc-8275-bce6f120bbd3.png)

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_optionmaster/pull/11
